# Generated by Django 5.2.5 on 2025-08-22 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitor.host')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('ppid', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('mem_rss', models.BigIntegerField(blank=True, null=True)),
                ('cmdline', models.TextField(blank=True, default='')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='monitor.snapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['captured_at'], name='monitor_sna_capture_59652e_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['pid', 'ppid'], name='monitor_pro_pid_54e0f8_idx'),
        ),
    ]
