# Generated by Django 5.2.5 on 2025-08-22 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=100)),
                ('os_version', models.TextField()),
                ('release', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=200)),
                ('cpu_count', models.IntegerField()),
                ('ram_total_gb', models.FloatField()),
                ('disk_total_gb', models.FloatField()),
                ('disk_used_gb', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='process',
            name='monitor_pro_pid_54e0f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='snapshot',
            name='monitor_sna_capture_59652e_idx',
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_info', to='monitor.host'),
        ),
    ]
